### ISSUE TITLE
Theine 3.10 cannot be launched on macOS 14.4

### ISSUE THREAD

**Issue by appaheadgmbh** [appaheadgmbh/support#1]
> When trying to start Theine on a newly set up Mac with macOS 14, it seems like nothing happens. The Theine icon does not appear in the menu bar.

**Comment by martinlexow** [comment]
**Fixed in Theine 3.11.** For the onboarding screen, I use `SpriteKit` to bring some life into the coffee beans. Unfortunately, part of this implementation led to the app crashing as soon as the onboarding screen was displayed, starting with macOS 14.4. This has now been fixed!
