### ISSUE TITLE
Mirror Magnet: Mission Control fails to render correct thumbnails

### ISSUE THREAD

**Issue by absoftware** [appaheadgmbh/support#10]
When Mirror Magnet is running, then Mission Control doesn't show applications in small Desktop Preview on top of the screen:

![image](https://github.com/user-attachments/assets/73701482-adc7-476a-b398-d8490b2504dc)

But it works when Mirror Magnet is off (VS Code is visible in small preview on top):

![image](https://github.com/user-attachments/assets/857090db-157d-4918-9d0e-a655ea4c7fcd)

**Comment by martinlexow** [comment]
Unfortunately, this is not a bug in Mirror Magnet, but (likely) in macOS itself. 

I requested a DTS ticket (Developer Tech Support) and filed feedback back in 2021 (in case anyone from Apple reads this → `FB9414607`).

> Mission Control fails to render correct thumbnails for its spaces.

I’ve been told that  _»This is a bug in Mission Control, it’s not consistent across spaces either«_.

Unfortunately, there has been no response to date.

**Comment by absoftware** [comment]
Thank you for the feedback. Hopefully it is not so crucial issue.
