### ISSUE TITLE
Add Language and Model Selection

### ISSUE THREAD

**Issue by airapy-yaro** [appaheadgmbh/support#11]
Hello,

What whisper model does the AI Transcription use? Would it be possible to add an option to select one? It would also be great to set the language of the source file and use the translation mode.

**Comment by martinlexow** [comment]
**Language selection**: With the update to [version 2.9](https://apps.apple.com/app/id1669896755), it is now possible to select a language. 

**Built-in models**: The app currently includes four models (_Small_ and _Medium_, as well as two additional models specifically optimized for English, all hardware-accelerated). 

There’s no UI to select a model directly. The app automatically selects the appropriate model based on the chosen language and the transcription priority (_Speed_ or _Precision_).

![Screenshot 2024-11-25 at 16 40 23](https://github.com/user-attachments/assets/18371b24-f7d6-4bb0-9e0e-976a3077ba52)

**Custom models**: There are currently no plans for a feature that allows custom models to be loaded. However, if I receive many requests for this in the future, I will gladly consider it as an option!
