### ISSUE TITLE
Cursor Pro is Damaged Error - Cannot Deploy App

### ISSUE THREAD

**Issue by michael-strohmaier** [appaheadgmbh/support#12]
Attempting to deploy app via Jamf.  App successfully installs, but force quits within minutes of being opened with dialog stating "Cursor Pro is damaged, please delete app and redownload".  Once the app opens, it requests an Apple ID sign-in and immediately force quits after that.

-Attempted deleting app and reinstalling, issue persists.
-Verified same issue occurs on test computer.
-Same issue occurs after recreating app in Jamf.

Our team paid for this app and cannot use it due to this issue, please help.

**Comment by martinlexow** [comment]
The good news first: **Version 2.12 (169) fixes the issue**, is currently under App Review, and will likely be available in the App Store in a few days. I apologize for the inconvenience. 

Until the new version is released, the following article might be useful: https://appahead.studio/help/keystroke-pro/the-app-prompts-to-login-fails-to-start-or-is-damaged 

In most cases, simply signing in with the Apple ID used to purchase the app should suffice.

I hope the app brings you a lot of joy!

**Comment by martinlexow** [comment]
Since version 2.12, which resolves the issue, is available in the App Store as of today, I’m closing this thread. Thank you for your feedback!
