### ISSUE TITLE
PolyCapture recordings are not displayed in “Recordings Organizer”

### ISSUE THREAD

**Issue by RainerZufall9393** [appaheadgmbh/support#13]
PolyCapture recordings are not displayed in “Recordings Organizer”.

They are displayed in the recording folder, but not in the organizer in the app.

![CleanShot 2024-09-20 at 02 09 43](https://github.com/user-attachments/assets/22b28bb7-fe7c-47cd-8a9a-a42d7edebb05)

**Comment by RainerZufall9393** [comment]
Update: The recordings are not saved in the recording folder either. Only worked with the first recording. All further recording attempts were not saved by the app.

Two microphones were also selected for recording during the first recording. Files were also created in the recording folder for both, but only one file contained data (sound).

**Comment by martinlexow** [comment]
Thank you for taking the time to report the bug, @RainerZufall9393 ! 

Based on your screenshots, I suspect you’re using the app on macOS 15 Sequoia (Beta?), is that correct? It would also be helpful to know if you’ve set a custom recordings location in the settings (see screenshot), and if so, what path (e.g., on an external hard drive, SSD, etc.) you’ve selected there. 

Thanks a lot for your support — I’ll try to fix the issue as quickly as possible!

![Screenshot 2024-09-20 at 09 52 53](https://github.com/user-attachments/assets/c0946cb6-2ce9-49c0-b8db-93e3f5683815)

**Comment by RainerZufall9393** [comment]
Hey Martin, macOS 15 is correct. Not the beta, but the official version that came out a few days ago.

I had selected a folder in the “Movies” parent folder as my recording location. 

I found out that the recordings are displayed in the Recording Organizer if I save the recordings in the Documents folder.

But as soon as I save in the Documents folder in a subfolder or somewhere other than Documents, these recordings are no longer displayed in the Recording Organizer.

There are problems with the microphones in any case. Although files are always created for them, they do not contain any data (and therefore no sound). This mainly affects my external microphone (connected to the MacBook via USB C).

Please let me know if you need any further details. :)

**Comment by martinlexow** [comment]
**Quick update**: I was able to fix the issue today where custom recording locations (especially after restarting the app) were not working properly. This affected both recording and viewing recordings in the Recording Organizer. The new version 1.2 is now under review and will hopefully be available in the App Store soon.

I’m aware of the issue with some microphones, and it is, of course, a top priority: I hope to develop a solution within the next week. In the meantime, I kindly ask for your patience. Thanks again for your feedback — it has really been a big help and has already made the app much better 🙏

**Comment by martinlexow** [comment]
Version 1.2 is available in the App Store as of today and fixes the issue with the Recordings Organizer. 

There is now a separate thread for the issue with empty microphone recordings (see: https://github.com/appaheadgmbh/support/issues/21) — I will address the problem there. I’m closing this issue as a result. 

Thank you for your support!

**Comment by RainerZufall9393** [comment]
Hey Martin,

Thanks for fixing the bug! Now it works for me. 🙏

I'm looking forward to the fix with the microphones. I can then use your app productively in my everyday work.

Thank you for your support and also for the app itself. Really good software that you have created!
