### ISSUE TITLE
PolyCapture feature suggestion: Overview of cameras and microphone levels during recording

### ISSUE THREAD

**Issue by RainerZufall9393** [appaheadgmbh/support#14]
It would be great to be able to see the camera recordings and microphone levels during recording.

That way you can always see exactly what the camera is recording and whether the microphones are clipping or not. It would also be useful to mark the microphone levels from green (“okay”) to yellow (“slightly clipping”) to red (“heavily clipping”).

It would be good if the camera recordings and microphone levels during recording could all be seen in a single overview without them being recorded (during screen recording).

It would be a dream if, when changing the Space on the screen, they could switch to the new Space as a Picture in Picture, so that you really always have everything in view, regardless of which Space you are in. Of course, the PIP should not be recorded either.

**Comment by martinlexow** [comment]
That’s a great idea, but its implementation is a bit more complex and will take some time!

May I follow up: Are you looking to see in detail what, for example, the cameras are recording, or are you more interested in knowing whether something is still being recorded? I’m asking because an audio level indicator could easily be placed in the menu bar icon without taking up much space — and perhaps also very small camera images.

**Comment by RainerZufall9393** [comment]
Hey Martin, for me personally it would be much better to be able to see exactly what is being recorded in a larger view than the menu bar.

Maybe it's easier for you to implement if the PIP idea is thrown overboard and the display is kept on a single space. But you're the expert on that.

With PIP would be my favorite, but even without it would be great. :)

**Comment by martinlexow** [comment]
This feature is still at the top of my to-do list. Since there are already several threads about it, I would like to merge them. I will therefore close this issue and continue tracking the topic [in this thread](https://github.com/appaheadgmbh/support/issues/42). Thanks again for your feedback!
