### ISSUE TITLE
PolyCapture window not opening when selecting settings from menubar 

### ISSUE THREAD

**Issue by Azyzraissi** [appaheadgmbh/support#15]
Paid user here. 
PolyCapture is running. 
It is visible in the menubar and dock. 
Selecting settings doesn't bring out the window. 
Clicking the dock icon also doesn't bring out the window. 

Fix : Right click on the dock icon, quit and launch again. 

Expected behavior: The window should appear and take focus immediately when selecting settings or clicking the icon on the dock. 

Thank you for the awesome product. Looking forward to future updates.

**Comment by martinlexow** [comment]
Hey Aziz Raissi — thanks for purchasing the app and for your kind words 🙏 You’re right, the settings window doesn’t appear in V1.0 when trying to open it via the menu bar icon. My apologies! I’ve just fixed the issue, and an update is on the way.
