### ISSUE TITLE
“Unlock Recording Features” menu item visible even though the app has been unlocked

### ISSUE THREAD

**Issue by Azyzraissi** [appaheadgmbh/support#16]
Every time I open PolyCapture, I have the option to unlock recording features even though I already did. 

Clicking on it doesn't do anything. It is like restoring purchases in games. 

Bug reproduce : Quit app and relaunch.

**Comment by martinlexow** [comment]
Hi @Azyzraissi — are you running the app on macOS 15 (Beta?) or 14?

**Comment by Azyzraissi** [comment]
Hello @martinlexow 

macOS 15.0 Stable build

**Comment by martinlexow** [comment]
Thanks again for reporting the bug, @Azyzraissi! I was able to fix the issue in version 1.3 of the app, and the update will be available in the App Store soon.

For the sake of completeness, I’d like to add: The issue only affected the menu of the Status Bar icon — in some cases, the “Unlock Recording Features” menu item was still shown even when the app had already been unlocked. The recording features themselves were always unlocked after a successful purchase.

**Comment by martinlexow** [comment]
Version 1.3 is now available in the App Store — I am therefore closing this ticket.
