### ISSUE TITLE
Adopt a more minimal UI design and use system fonts

### ISSUE THREAD

**Issue by stevenorechow** [appaheadgmbh/support#17]
Polycapture seems great so far. This is more of a pet peeve than an issue (perhaps I'm just used to Cleanshot), But please consider implementing a more minimalistic design jin future updates (Eg. System fonts, buttons etc). Just a thought, please feel free to close this issue once you see it.

**Comment by martinlexow** [comment]
Thank you for the suggestion! So far, I haven’t planned for themes that would allow for a simpler UI, for example. However, I’d like to keep this issue/thread open for a while in case others share this request, so I can consider it if needed.

**Comment by wesbos** [comment]
Keep the UI, most apps dont have soul like this one any more

**Comment by martinlexow** [comment]
Since no one else has requested this (not even through other channels), I’m closing this thread for now.
