### ISSUE TITLE
Add mouse cursor to record (screen, app, screen area)

### ISSUE THREAD

**Issue by AlexRVillalobos** [appaheadgmbh/support#20]
Now screenshots do not record the mouse cursor. 

Please consider it optional to record the mouse cursor (or not) when recording a screen, section of the screen or application. It would also be nice to have the possibility to add some effect when clicking.

Thanks a lot

**Comment by martinlexow** [comment]
In version 1.3, it is now possible to optionally show or hide the macOS cursor in screen recordings. The toggle is located in the context menu and will be enabled by default.
![Screenshot 2024-09-25 at 15 02 49](https://github.com/user-attachments/assets/20135c23-8a8b-4666-9845-e7760d0ee1a6)

**Comment by AlexRVillalobos** [comment]
Appreciate!

**Comment by martinlexow** [comment]
Version 1.3 is now available in the App Store — I am therefore closing this ticket.
