### ISSUE TITLE
Recording produces an empty audio file (.caf)

### ISSUE THREAD

**Issue by AlexRVillalobos** [appaheadgmbh/support#21]
when i record audio from webcam microphone, .caf file is empty. With 00:00 seconds

HD Pro Webcam C920
Mac mini 2018
Sequoia 15.0

**Comment by AlexRVillalobos** [comment]
Please consider as aa option to save as .mp3 or .wav file. Thanks

**Comment by martinlexow** [comment]
Could you please also let me know whether your test involved a very short recording (a duration of a few seconds) or if it was a longer session that resulted in a 0-second recording?

**Comment by wesbos** [comment]
All of my recordings with an external mic are also giving me empty .caf files. The mic shows up and the levels are bouncing in preview. 

Build in macbook pro mic works fine.


<img width="685" alt="Screenshot 2024-09-27 at 10 57 45 AM" src="https://github.com/user-attachments/assets/f5cb5c00-14f7-4cc1-9a14-64f1bc173cda">

<img width="439" alt="Screenshot 2024-09-27 at 10 57 54 AM" src="https://github.com/user-attachments/assets/7eafb734-33f8-4c4d-9fd0-d10f7e9e4387">

**Comment by OursNoir600** [comment]
I have exactly the same problem! I have several external microphones and I can't get any sound. Even with just one external microphone, nothing works.

MAC OS 15
Mac mini M1

![Capture d’écran, le 2024-09-30 à 10 08 46](https://github.com/user-attachments/assets/1127b28b-3325-46a5-a6ac-302e6aa5d256)

**Comment by OursNoir600** [comment]
I did a test again and if I record the sound and the screen only, everything works fine! But as soon as I add external cameras nothing works anymore in terms of sound.

**Comment by OursNoir600** [comment]
> I did a test again and if I record the sound and the screen only, everything works fine! But as soon as I add external cameras nothing works anymore in terms of sound.

I did a test again and if I record the sound and an external camera only, everything works fine!

**Comment by OursNoir600** [comment]
> > I did a test again and if I record the sound and the screen only, everything works fine! But as soon as I add external cameras nothing works anymore in terms of sound.
> 
> I did a test again and if I record the sound and an external camera only, everything works fine!

I just tested again, and if I quit PolyCapture and open and use it everything works fine! But for the next recording I will have to quit it again!

**Comment by martinlexow** [comment]
Thank you everyone for your detailed tests, and I apologize that the app is having issues with external microphone recordings on macOS 15 in version 1.4. 

I was able to identify the problem in the meantime, and a fix is on the way. I’d like to continue the discussion in the “[Distorted Audio or Empty Recording When Using External Microphones](https://github.com/appaheadgmbh/support/issues/23)” issue, as it’s related to the same error, and will therefore close this issue.

PS: I can confirm that @OursNoir600’s workaround works — the first recording usually sounds fine, and the issues only occur with subsequent ones. Therefore, restarting the app helps.
