### ISSUE TITLE
Distorted Audio or Empty Recording When Using External Microphones

### ISSUE THREAD

**Issue by martinlexow** [appaheadgmbh/support#23]
It seems that using certain microphone models leads to distorted-sounding recordings. 

The affected devices, as far as I know, are the `Shure MX7` and the `RØDE PodMic`.

**Edit**: The issue seems to potentially affect all external microphones connected via USB. The resulting recordings either sound overdriven and distorted, or the file remains completely empty and cannot be played back.

**Comment by martinlexow** [comment]
Tried to reproduce this bug today with the `RØDE PodMic` on macOS 14.7 without luck — everything sounds excellent.

**Comment by martinlexow** [comment]
Recording with a `Shure MX7` also sounds good now. 

Starting with app version 1.3, audio recordings in `Best Performance` quality mode will be captured in the `kAudioFormatMPEG4AAC` format (Compressed AAC), whereas in `Best Quality` mode, they will be recorded as uncompressed audio in the `kAudioFormatLinearPCM` format (Linear PCM).

The individual properties of the selected microphone are automatically taken into account. To view these, I’ve designed a new interface. It can be found under: `Settings` → `Devices` → `Microphones`. Then double-click on the respective microphone. Note: It must be connected to your Mac.
![Screenshot 2024-09-26 at 09 38 27](https://github.com/user-attachments/assets/fe84047e-366e-414c-bfe5-dd5e52c6b83a)

**Comment by martinlexow** [comment]
I’m reopening this thread because it seems that in at least one case, there is still an issue with distortion (?) on the Shure MX7 (`AppleUSBAudioEngine:Shure Inc:Shure MV7:3130000:2,1`).

Attached is a sound file with the interference noises as an example of the described issue:
[mic-CFCCBB97-4217-4672-A2CF-AEA1D4361E6F.zip](https://github.com/user-attachments/files/17146841/mic-CFCCBB97-4217-4672-A2CF-AEA1D4361E6F.zip)

**Comment by 1castro** [comment]
I’ll jump in here as I’m desperately trying to get an Elgato Wave XLR microphone to work properly. The recordings are just full of strong noise and interference. In other applications, the mic works without any issues.

**Comment by martinlexow** [comment]
After thoroughly investigating the issue, I no longer believe that specific microphones are affected but rather potentially all externally connected ones via USB. Additionally, the issue seems to occur more frequently on macOS 15.

I wasn’t able to reproduce the problem with the internal MacBook microphone or with microphones connected via the headphone jack — those seem to work great in every scenario.

One thing that stands out is that recordings are often distorted starting from the second attempt. The first recording, however, seems to work reliably in most cases. A workaround for now could be to restart the app after the first recording. Of course, this is not an acceptable long-term solution.

The underlying issue seems to occur directly in `CoreAudio` and its `AudioConverter`. The log in the console reads:
> Input data proc returned inconsistent 512 packets for 2048 bytes; at 3 bytes per packet, that is actually 682 packets

In case someone from Apple reads this: I’ve filed a feedback → `FB15333298`

My next step will be to request code-level support in the hope of shipping a solution as soon as possible. I’ll keep you updated here!

**Comment by martinlexow** [comment]
I’ve managed to come up with a solution in the meantime, and I’ve got a few more gray hairs to show for it. Version 1.5 of the app is now ‘In Review’ and will hopefully be available on the App Store soon.

**Comment by martinlexow** [comment]
Version 1.5 is [now available](https://apps.apple.com/app/id6504193234) on the App Store and has been able to resolve the microphone issue on all of my test devices — I’d be happy if you could try it out and let me know about your experiences!

**Comment by martinlexow** [comment]
As this issue appears to be permanently resolved, I’m closing the thread! 🥳
