### ISSUE TITLE
Colors are muted when screen recording

### ISSUE THREAD

**Issue by wesbos** [appaheadgmbh/support#29]
When recording with quality set to "best quality", the recorded colours are muted.

See here, imported into screenflow, the finder preview, and the actual screen. 

<img width="1101" alt="Screenshot 2024-09-26 at 4 18 58 PM" src="https://github.com/user-attachments/assets/c40833b5-c840-4eae-ac1c-eab5591e7cb4">

I'm on Mac OS 15.0

**Comment by martinlexow** [comment]
I was able to reproduce the issue on my end and am now working on a solution!

**Comment by martinlexow** [comment]
I believe I was able to resolve the issue in the meantime. I would like to discuss everything else in the [“Video Quality” issue](https://github.com/appaheadgmbh/support/issues/31), as the topics are related. Therefore, I’m closing this thread.

Thank you for bringing the issue to my attention. The comparison image was very helpful!
