### ISSUE TITLE
Suggestion: Name window recordings with the App name

### ISSUE THREAD

**Issue by wesbos** [appaheadgmbh/support#30]
These files would be really nice if they said the app name, like they do in the preview:

<img width="464" alt="Screenshot 2024-09-26 at 4 23 22 PM" src="https://github.com/user-attachments/assets/7070eac8-9e23-4928-bf1b-4cad347d80c5">

<img width="229" alt="Screenshot 2024-09-26 at 4 24 06 PM" src="https://github.com/user-attachments/assets/87d06d94-f8c1-4855-a40b-6c9743890d63">

**Comment by martinlexow** [comment]
Implemented that immediately in version 1.4 — the update will likely be available on the App Store in the next few days.

The new file name scheme is:
"screen-window-`appName`-`windowTitle`-`setupID`.mov"

**Comment by wesbos** [comment]
Amazing! Thank you

**Comment by martinlexow** [comment]
Version 1.4 went live this morning, so I’m closing this ticket. Thank you for your feedback! 🙏
