### ISSUE TITLE
Switching app windows in the Screens tab doesn’t work consistently

### ISSUE THREAD

**Issue by wesbos** [appaheadgmbh/support#33]
Switching windows between the same app does not consistently switch. I've recorded a video detailing the issue here: 

https://f000.backblazeb2.com/file/wes-dropshare/CleanShot-2024-09-27-at-10.50.00

**Comment by martinlexow** [comment]
Super helpful video, thank you so much for your efforts! I also noticed some UI bugs in it that I was able to fix right away thanks to the video. 

I have one more question about switching windows: Can the issue be reproduced with other apps on your end, or only with Edge? On my test Macs, switching works without any problems. Unfortunately, I don’t have Edge installed.

**Comment by wesbos** [comment]
i restarted the app and I'm no longer able to replicate the bug with any app - I tested with Finder, VS Code and MS Edge

Video: https://share.cleanshot.com/kmXr3GQH

**Comment by martinlexow** [comment]
I now also encountered the issue once, but I wasn’t able to reproduce it again. The best workaround for now seems to be, as described in your video, to leave the Screen tab once and then open it again.

**Comment by wesbos** [comment]
Thanks - Ill keep an eye on it and see if I can find any way to produce it. Ill close for now
