### ISSUE TITLE
Recording Monitor: Show Audio Levels in Recording UI

### ISSUE THREAD

**Issue by wesbos** [appaheadgmbh/support#34]
This UI:

<img width="207" alt="Screenshot 2024-09-27 at 11 00 27 AM" src="https://github.com/user-attachments/assets/359b02da-fbca-4e79-b785-c08ade376a60">

Inside the recording UI:

<img width="522" alt="Screenshot 2024-09-27 at 11 00 14 AM" src="https://github.com/user-attachments/assets/e29cbb7b-7a0c-49bb-b38b-a748f604dee4">

My biggest fear is that my audio isn't actually capturing - so I like to see my levels bounce and know they are being captured

**Comment by martinlexow** [comment]
Excellent idea. I will definitely implement that in one of the next versions.

**Comment by martinlexow** [comment]
This feature is still at the top of my to-do list. Since there are already several threads about it, I would like to merge them. I will therefore close this issue and continue tracking the topic [in this thread](https://github.com/appaheadgmbh/support/issues/42). Thanks again for your feedback!
