### ISSUE TITLE
PolyCapture video and audio not synchronized

### ISSUE THREAD

**Issue by RainerZufall9393** [appaheadgmbh/support#38]
Hey Martin, when I record something with PolyCapture, the audio files are always slightly longer (2 sec +) than the video files and therefore not synchronized. Could you take a look at this? Is it the same for you?

PolyCapture Version 1.5

**Comment by martinlexow** [comment]
The slight difference in recording lengths (max. 1-2 seconds, often significantly less) is expected behavior of the app. Depending on the hardware used, not all sources may be available at the exact moment when “Record” is pressed. The app already takes several measures to minimize this latency.

I’m working on implementing an option for automatic clip synchronization in post-production, along with the planned feature for merging individual tracks into a single file.

**Comment by RainerZufall9393** [comment]
All right, thanks for the explanation 👍

**Comment by MatsWiese** [comment]
Hello there,
as I stumbled over this issue as well, I want to ask what will be the best way to sync them? You say, the sources may not be available at the same time, so the start-time differs. Can we assume the end-points for all files will be (exactly) the same? So in post, we can adjust for the track-ends?

I'm happy, I found your app. The only annoying thing so far for me was seeing the price increase before purchase as black friday is over 🙈

**Comment by martinlexow** [comment]
The end times can also theoretically vary slightly, but if they do, the difference will be much smaller than with the start times. 

The best way to sync recordings in post-production at the moment is the _classic method™_: manually creating audio-visual cues. For example, clapping at the beginning of the recording and aligning the different tracks with the peaks. Apps like Final Cut Pro can do this (based on audio, as far as I know) automatically. However, this becomes especially challenging with screen recordings. I’m fully aware that PolyCapture has significant improvements to make in this area.

The good news is: **I’m already working on a sync and merge feature.** I just need another week or two to get it right. You can [follow my progress on this here](https://github.com/appaheadgmbh/support/issues/28).

**Comment by MatsWiese** [comment]
Classic method for the win! 😁

Thank you. Looking forward to this feature.
