### ISSUE TITLE
PolyCapture audio and video length not the same

### ISSUE THREAD

**Issue by pthieu** [appaheadgmbh/support#46]
My setup:
- USB mic
- M1 Pro Built-in screen
- USB HDMI capture-card to my camera's HDMI-out

The webcam capture is always shorter (in duration) than the audio and screen capture video, so syncing it in post is a bit annoying (especially because there's no audio to align with).

This would be solved by allowing the audio to get embedded into one of the video files (in this case, the camera file) or by resolving the duration issue itself.

![CleanShot 2024-10-29 at 23 58 58](https://github.com/user-attachments/assets/a4872538-57df-41a7-aaff-c60283cf8faf)

App is amazing otherwise, exactly what I'm looking for.

**Comment by pthieu** [comment]
Seems like a good additional use-case for embedding the audio into the video: https://github.com/appaheadgmbh/support/issues/28

My use case would be to enable a setting to embed the audio to all or a specific video source so that it does it during recording instead of a post-step (assuming it will take additional time).

**Comment by martinlexow** [comment]
A slight difference in recording lengths is an (unfortunate) expected behavior of the app, as [described here](https://github.com/appaheadgmbh/support/issues/38#issuecomment-2402065137).

I completely understand your request for merging and synchronizing individual tracks. I’ll be implementing a feature for this asap.

**Comment by pthieu** [comment]
@martinlexow thanks! looking forward to it

**Comment by martinlexow** [comment]
With the latest update, video and audio tracks can now be synchronized and merged into a single file. I’ll explain the details in [this thread](https://github.com/appaheadgmbh/support/issues/28)—where I’d also be happy to discuss the topic further if needed—so I’m closing this thread for now. Thanks again for your feedback, @pthieu! 🙏
