### ISSUE TITLE
AI Transcription: Apple ID sigin-in loop and App reporting it's damaged

### ISSUE THREAD

**Issue by Gruberman** [appaheadgmbh/support#49]
—
I am using AI Transcription 2.5 (Build 42) on macOS Version 14.7.1 (Build 23H222) running on an M2 Mac Studio (Mac14,14)

The app refuses to run now, even after many months of use without a problem. Maybe it was the update to Sonoma 14.7.1? Launching the app immediately brings up a “sign in with your Apple ID” dialog… when I enter my username and password and click Sign In, the dialog immediately reappears as if I haven’t done anything. Nothing I do makes it happy for two tries; on the third try, it seems to accept the Apple ID input and then immediately quits with a “this app is damaged - delete it and re-download from the App Store” error message.

If I click cancel instead of entering my Apple ID, I can at least start to process a file… until the app suddenly quits again, with the “this app is damaged” message.

I used AppCleaner to remove the app and all files associated with it, cleaned caches, restarted, and re-downloaded the app from the App Store, and the same thing happened. I even gave the app Full Disk Access in Privacy and Security, with no change.

![Apple ID Sign In](https://github.com/user-attachments/assets/e2b1852b-86f0-49b3-8ac5-f7185ee327ec)
![Damaged](https://github.com/user-attachments/assets/c0f37a1d-724a-4dd6-8e44-025b015bab7a)

**Comment by martinlexow** [comment]
Hi Ken — does [this article](https://appahead.studio/help/keystroke-pro/the-app-prompts-to-login-fails-to-start-or-is-damaged) may help?

Usually, signing in with the Apple-ID you’ve purchased the app with should solve the issue (have you may changed your Apple-ID in the meantime?).

I’m also already working on an update that will be released soon and should resolve the issue too.

**Comment by martinlexow** [comment]
This problem has been resolved since AI Transcription 2.8.
