### ISSUE TITLE
Merge Audio/Videos of Screen or Camera recordings as a single file

### ISSUE THREAD

**Issue by pzeepzee** [appaheadgmbh/support#51]
Hi,
I am testing out PolyCapture, love the features of the app, but have a major deal breaker, - that is, the audio file and vid files of screen recordings or camera recordings are captured as separate files within a folder. Wish it was a single file for each recording, so as to remove the need to use another software to merge the audio/vid files.
Is this something you can look into pls?
Thanks

<img width="731" alt="ScreenFloat Shot of Finder at 4 Dec 2024 at 13_02_47" src="https://github.com/user-attachments/assets/1b1e9068-0326-46a5-85ac-ff7457cfa85b">

**Comment by MatsWiese** [comment]
Hi,
I don't want to undermine your opinion, but also share mine. For me, these splitted files are what I looked for, as I want to edit them together afterwards. I tried OBS Studio before, where you get all as one file, and couldn't find a way to save them individually. Maybe try OBS?

**Comment by martinlexow** [comment]
Hi @pzeepzee  — the recordings are saved in separate files to allow maximum flexibility in post-production: For example, it’s not automatically clear where each video should appear (since any number of videos can be added), or how the audio tracks should be mixed together. 

However, I completely understand your desire to have just a single file in the end. For this reason, I’m currently working on a merge feature that will enable exactly that. You can find [a preview of how this will look here](https://github.com/appaheadgmbh/support/issues/28) — and I’ll notify everyone in the linked thread once the feature is ready.

**Comment by pzeepzee** [comment]
> Hi, I don't want to undermine your opinion, but also share mine. For me, these splitted files are what I looked for, as I want to edit them together afterwards. I tried OBS Studio before, where you get all as one file, and couldn't find a way to save them individually. Maybe try OBS?

Oh, didn't think of that, but makes sense for certain use cases like yours which I believe might do with audio/vid  production or the likes? 
My use case is for capturing meetings on a 9to5, so having it merged is more useful to me, as I can put a voice to the names/faces quickly, rather than doing that elsewhere.
I hope we can have both options in the future, cheers

**Comment by pzeepzee** [comment]
> Hi @pzeepzee — the recordings are saved in separate files to allow maximum flexibility in post-production: For example, it’s not automatically clear where each video should appear (since any number of videos can be added), or how the audio tracks should be mixed together.
> 
> However, I completely understand your desire to have just a single file in the end. For this reason, I’m currently working on a merge feature that will enable exactly that. You can find [a preview of how this will look here](https://github.com/appaheadgmbh/support/issues/28) — and I’ll notify everyone in the linked thread once the feature is ready.

Thanks Martin for the quick response, I can now see why you left it as separate files, since the user might be recording  from multiples sources during a session. Having looked at the preview in your link above, makes a lot of sense to have the option to merge post capture at the click of a button, or maybe a dialog to choose pre-recording?
Anyways, pre or post merging is fine by me, as long as I don't have to export to another app to do, am cool.
Thanks for creating such a beautiful app, cheers
