### ISSUE TITLE
How To Record FaceTime Calls

### ISSUE THREAD

**Issue by MatsWiese** [appaheadgmbh/support#52]
I tried to record a coding-session with a friend. I set up PolyCapture for my second screen and the facetime window. I set it to record systemsounds, but unfortunately it didn't record the voice of my friend. I couldn't add facetime as soundsource either.

is there a way?

**Comment by MatsWiese** [comment]
Seems like its an Apple-Thing to prevent audio-recording in FaceTime-calls.
So my friend will need to record his own audio unfortunately.

**Comment by martinlexow** [comment]
I’d like to continue discussing your question [in this thread](https://github.com/appaheadgmbh/support/issues/53), as I believe both topics refer to the same issue, and will therefore close this thread. 🙏
