### ISSUE TITLE
Dialog stating Cursor Pro is Damaged

### ISSUE THREAD

**Issue by KJ5AJB** [appaheadgmbh/support#8]
After launching the app I get a dialog wanting me to sign into Apple media services, which is strange. 
After getting past that, the app will crash and I get a dialog stating Cursor Pro is damaged and should be deleted.
I've tried deleting the app and reinstalling but still the same.

This is on a Mac mini M2 Pro, running the latest OS.
It works fine on my M1 Mac mini, running the same OS.

**Comment by michael-strohmaier** [comment]
I am having the same issue on two different M1 Machines.  Any update on this?

**Comment by martinlexow** [comment]
I am closing this thread, as I have already responded to it here → https://github.com/appaheadgmbh/support/issues/12#issuecomment-2363528834

> Version 2.12 (169) fixes the issue

**Comment by KJ5AJB** [comment]
Thanks looking forward to the update.
