### ISSUE TITLE
Mirror Magnet and Keystroke Pro deactivate Rectangle app

### ISSUE THREAD

**Issue by absoftware** [appaheadgmbh/support#9]
App Rectangle https://rectangleapp.com/ no longer works when Mirror Magnet or Keystroke Pro are running.

Everything is going back fine immediately when I turn off Mirror Magent and Keystroke Pro.

So I cannot use hot corners to position the view on the screen. They were working together some time ago. So there is regression after some of the last updates.

Steps:

1. Keep Rectangle app running.
2. Enable Mirror Magnet or Keystroke Pro
3. Rectangle app is not working [bug]
4. Exit Mirror Magnet or Keystroke Pro
5. Rectangle app is working OK

macOS Ventura on Intel-based iMac

**Comment by absoftware** [comment]
I was testing many alternatives to have camera preview on the screen in time of recording, but none of them is so aesthetic like yours. But I use Rectangle and I used to it. Please prioritise this fix. I can implement fix for free if you trust me as I'm Objective-C/Swift developer with many years of experience.

I tested Loom, Snagit, Camtasia, DemoCreator and probably 10 more. Lost for tests a few days. Their tools are more advanced but they still are not so good like your product. They have limited number of shapes for camera preview with strange proportions, no camera zoom, no alignments, snap areas, no margin around camera preview, performance problems,  camera disappears when switching between virtual desktops, no disappearing when mouse is on top. So you have almost perfect product, but just this one bug.

**Comment by martinlexow** [comment]
Hi Ariel — thank you so much for your kind feedback! 

I haven’t made any major changes to how Keystroke Pro and Mirror Magnet work over the past few months. So, if you’ve noticed a change in how they interact with other apps, it’s probably due to the implementation of those other apps. 

Personally, I don’t have any experience with Rectangle and unfortunately can’t offer support for it. I’m really sorry that I can’t provide a solution.

**Comment by absoftware** [comment]
I reported this issue here, not in Rectangle, because making some analysis, all applications having impact on macOS desktop, work probably in a layers:

- layer on top with Mirror Magnet eats mouse events and doesn't pass them to lower layers (I mean some specific events related to the edge of the screen, some edge gesture recognisers, or something like that)
- layer below with Rectangle no longer receives these events when Mirror Magnet is launched

This issue is older than a few months, because I had a long break with making my videos. But I have in my old videos that both work: hot corners for Rectangle and Mirror Magnet in the same time. Later (1-1.5 year ago) some update arrived and it stopped to be working.

I also use macOS Ventura still on my iMac... maybe it has some impact on this also. New Mac Studio will arrive soon, so I will check with the newest macOS.

But this issue is very crucial for my "business" because I would like to go back to my online courses right now. Alternatives are much worse than your product.
